package com.pss.backend.enums;

public enum Modulo {

    GESTION_USUARIOS,
    GESTION_SERVICIOS,
    GESTION_SOLICITUDES,
    GESTION_INVENTARIO,
    GESTION_PROVEEDORES,
    GESTION_CLIENTES,
    GESTION_CATEGORIAS,
    GESTION_PRECIOS,
    VER_REPORTES,
    CONFIGURAR_SISTEMA,
    VER_BITACORA,
    CREAR_USUARIOS,
    ELIMINAR_USUARIOS,
    EDITAR_USUARIOS,

    VER_MIS_SERVICIOS,
    EDITAR_MIS_SERVICIOS,
    ELIMINAR_MIS_SERVICIOS,
    RESPONDER_SOLICITUDES,
    VER_SOLICITUDES_RECIBIDAS,
    ACTUALIZAR_ESTADO_SERVICIO,
    VER_MIS_CALIFICACIONES,
    ACTUALIZAR_DISPONIBILIDAD,
    VER_PEDIDOS_ASIGNADOS,
    GESTION_HORARIOS,
    
    CREAR_SOLICITUDES,
    VER_SOLICITUDES,
    EDITAR_SOLICITUDES,
    CANCELAR_SOLICITUDES,
    VER_SERVICIOS_DISPONIBLES,
    BUSCAR_PROVEEDORES,
    VER_HISTORIAL_SOLICITUDES,
    CALIFICAR_SERVICIOS,
    VER_DETALLES_SERVICIO,
    REALIZAR_PAGOS,
    VER_MIS_FACTURAS,
    EDITAR_MI_PERFIL;
}
